### ISSUE TITLE
Build fails out of the box on Windows

### ISSUE THREAD

**Issue by tobiasmuehl** [gaearon/react-hot-boilerplate#75]
I'm on Windows 10 x64 and can't get the boilerplate to run.

## Error on master branch

on commit `c7a808185b372a27dfe5758b340578c95922f74e`
```
git clone git@github.com:gaearon/react-hot-boilerplate.git
cd react-hot-boilerplate
npm i
npm start
```
 ```
ERROR in ./src/index.js
Module parse failed: D:\Work\OriginalOrCopy\react-hot-boilerplate\src\index.js Unexpected token (5:16)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (5:16)
    at Parser.pp.raise (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.unexpected (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:1483:8)
    at Parser.pp.parseExprAtom (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:204:17)
    at Parser.pp.parseExprOps (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:110:19)
    at Parser.pp.parseExprList (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:657:23)
    at Parser.pp.parseSubscripts (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:249:29)

```
[(Full log here)](https://gist.github.com/tobiasmuehl/d51164cbe7076b242cb464047e705885)

## Same thing happens on version 3-alpha

on commit `f134ff335d26f1b0369e65a9309b4ec1a38a2581`

```
ERROR in ./src/index.js
Module parse failed: D:\Work\OriginalOrCopy\react-hot-boilerplate\src\index.js Unexpected token (8:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (8:2)
    at Parser.pp.raise (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:920:13)
    at Parser.pp.unexpected (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:1483:8)
    at Parser.pp.parseExprAtom (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:204:17)
    at Parser.pp.parseExprOps (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:110:19)
    at Parser.pp.parseExprList (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:657:23)
    at Parser.pp.parseSubscripts (C:\d\Work\OriginalOrCopy\react-hot-boilerplate\node_modules\webpack\node_modules\acorn\dist\acorn.js:249:29)
```
[Full log here](https://gist.github.com/tobiasmuehl/bd5003fce0618f9b2dd7b206b0a99cc7)

**Comment by equicolor** [comment]
I get same error

**Comment by flcl42** [comment]
Very weird: got same error 
`Module parse failed: D:\sandbox\react-hot-boilerplate\src\index.js`
while trying debug from VS Code (internally it runs node like `--debug-brk=12312 server.js` and connects to debugger), but if I run from **console** it works fine.

Windows 8, node 6.2.2.

**Comment by Ctrl-J** [comment]
I get the same error if I use node 6.0.0 or greater on Windows 8.1

I believe it's an issue with babel, as I've seen the same behavior in other projects. Something is wrong with parsing the JSX. Node 5.12.0 works without issues however.

**Comment by myleschuahiock** [comment]
I get exactly the same error. I'm using Node 6.2.2.

**Comment by maestroh** [comment]
I could get past the error by changing the extensions from .js to .jsx for App.js and index.js. I also updated config to test for jsx. Now I get the error: "Module not found: Error: Cannot resolve 'file' or 'directory' ./src/index in c:\p\react-hot-boilerplate"

**Comment by simeg** [comment]
I get the same error on Mac using node v6.3.1 and npm v3.10.3. I have tried re-installing both node and npm multiple times without success.

**Comment by doomietrue** [comment]
The same error, Windows 7, node 6.0.0 and npm 3.8.6

**Comment by uripre** [comment]
Same error. Windows 10, node 6.4.0, npm 3.3.12.

**Comment by ifElser** [comment]
same error in Ubuntu server 14.04 LTS, node v7.2.0
`
ERROR in multi main
Module not found: Error: Can't resolve 'react-hot-loader/patch' in '/home/elser/node/projects/publicsonar/react-test-app/development/source'
@ multi main
`

**Comment by unional** [comment]
Updating node to v6.9.1 fixed the issue for me

**Comment by calesce** [comment]
Are people still seeing this on `master` or `next` branches?

**Comment by ijscoman1337** [comment]
When trying to run NPM Start

ERROR in ./src/index.js
Module build failed: TypeError: [BABEL] /Users/j/Code/React/scoreboard/src/index.js: Invalid options type for /Users/j/Code/React/scoreboard/node_modules/babel-preset-airbnb/index.js

**Comment by calesce** [comment]
@ijscoman1337 we don't use `babel-preset-airbnb`, not sure where that's coming from.
